### ISSUE TITLE
Extra bond displayed in nglview

### ISSUE THREAD

**Issue by natlosada** [nglviewer/nglview#1013]
I have attached below the screenshot of the code I used to display 3fgu in nglview in jupyter and the display shows an impossible extra bond. This extra bond is not seen when loading in Mol* on the PDB site so I think it's safe to assume it's something in the nglview system. Just wanted to inform in case some bigger problem needs to be resolved.

This only happens in the default display after this code is used:

filepath = os.path.join('PDB_files', '3fgu.pdb')
view = nv.show_file(filepath)
view

![jupyterhub_extrabond_error](https://user-images.githubusercontent.com/100295575/155341688-443eb299-39e5-44ca-ab21-ded857ad93aa.png)

**Comment by hainm** [comment]
hi @natlosada, thank you for your report. I've opened an issue in `NGL` repo: https://github.com/nglviewer/ngl/issues/914

**Comment by hainm** [comment]
It's likely that `nglview` needs to update `NGL` version. The known working version of NGL is `2.0.0-dev.37`

**Comment by UnWaDo** [comment]
I'm having the same issue: additional bonds are drawn between molecules not even close to each other

I first thought that it is due to a periodic conditions, but there are also bonds in the bulk from definitely different molecules

https://nglviewer.org/ngl/ shows the molecule in a correct way

I'm using nglview 3.0.8 and python 3.10.8

<img width="357" alt="image" src="https://github.com/nglviewer/nglview/assets/37781498/549e9d6b-b7f3-4109-abaa-6850dfe0d43f">

**Comment by hainm** [comment]
Thanks for your report. It might be that nglview is using older NGL
version. I will check.

**Comment by hainm** [comment]
nglview `3.1.1` should (likely) resolve that since I've updated the latest NGL version.
