### ISSUE TITLE
Does not work in Google Colab

### ISSUE THREAD

**Issue by AlexeyG** [nglviewer/nglview#816]
nglview does not seem to work in a Google colaboratory. Issuing the below commands (after the package was successfully installed via pip install) just crashes the runtime.

```
import nglview
import ipywidgets
nglview.show_pdbid('3pqr')
```

**Comment by hainm** [comment]
hi, I am not sure if codelab supports 3rd party software like `nglview`. Does that lab work with ipywidgets-based bqplot or ipyvolume or something else?  The issue here is that `pip install nglview` is not sufficient to make `nglview` work. User normally need to "activate" the javascript code via `jupyter-nbextension enable nglview --py --sys-prefix` (don't ask me why because I don't know why we really need that :D). That step should be done before opening the notebook.

**Comment by hainm** [comment]
It seems that google people need to add `nglview` by themself: https://github.com/googlecolab/colabtools/issues/60#issuecomment-427765759

**Comment by Taoaoxiang** [comment]
@AlexeyG Runtime says "Busy", and the little icon keeps spinning forever. 
Mine is using conda to install nglview. 
`!conda install -y --prefix /usr/local nglview -c conda-forge`
I think Colab doesn't support a lot of packages. Anyways, thank you for your issue report. Otherwise I have to wait, like, forever.

**Comment by hainm** [comment]
I go ahead closing this case since it's out of our control. Thanks for asking.

**Comment by hainm** [comment]
Guys, FYI: https://github.com/googlecolab/colab-cdn-widget-manager/pull/14
