### ISSUE TITLE
Race condition: view.gui_style = 'ngl'

### ISSUE THREAD

**Issue by hainm** [nglviewer/nglview#939]
https://github.com/nglviewer/nglview/issues/901#issuecomment-747163835

From @zacharyrs 

> Hey - I'm having a little difficulty with the GUI (#830).
> 
> Using the exact code in the PR gives me a blank GUI on first run, but then succeeds on the second.
> ![Peek 2020-12-17 15-23](https://user-images.githubusercontent.com/10497077/102435665-e447d500-407b-11eb-9cef-859fed1db8f4.gif)
> 
> Console doesn't show any errors.
> I've indicated 1 and 2 for the 1st and 2nd cell runs.
> ![Screenshot from 2020-12-17 15-27-24](https://user-images.githubusercontent.com/10497077/102436086-b020e400-407c-11eb-83e7-7e75894a7b36.png)

**Comment by zacharyrs** [comment]
Hey, I managed to figure out the cause by stepping through with debug tools on Chrome.

The issue is in [line 263 of gui.js](https://github.com/nglviewer/nglview/blob/5136ac22c530adcef0525559b7aeb44eefb261ed/js/src/gui.js#L263).

The styles aren't loaded at the time that is called.
Hence the sidebar is position-relative, and expands to the same width as the container.
Then the subsequent subtraction `ew - sw` gives a zero.

I'm not too sure where the style gets loaded.
It needs to be shifted to prior to the `handleResizeInNotebook` call - or hardcode `sw` as `300px`, given that's [its eventual value](https://github.com/nglviewer/nglview/blob/2cd42979e0c39c163b6728f59ffea6e9d8cd56db/nglview/theme/main.css#L408).

**Comment by hainm** [comment]
Thanks @zacharyrs  for your investigation.

> I'm not too sure where the style gets loaded.

`view.gui_style = 'ngl'` will trigger a function call to JS code: https://github.com/nglviewer/nglview/blob/master/nglview/theme/theme.py#L61

which is here: https://github.com/nglviewer/nglview/blob/2cd42979e0c39c163b6728f59ffea6e9d8cd56db/js/src/theme.ts#L29

Are you using traditional notebook or lab? and which version? I am trying many times in my notebook but I can not reproduce the issue (but I am sure that there is always a race condition somewhere in nglview).

**Comment by hainm** [comment]
> I am trying many times in my notebook but I can not reproduce the issue 

Never mind. I can reproduce the issue in lab.

**Comment by zacharyrs** [comment]
Yes I'm working in jupyter lab.

**Comment by hainm** [comment]
> Maybe if sw == ew just set sw as 300px?

yeah, sounds good.
